stages:
  - deploy

before_script:
  - touch .env
  - echo VUE_APP_API_ENV=$DEPLOY_VUE_APP_API_ENV >> .env
  - echo VUE_APP_API_PATH=$DEPLOY_VUE_APP_API_PATH >> .env

deploy:develop:
  environment:
    name: develop
    url: $DEV_ENVIRONMENT_URL
  variables:
    DEPLOY_VUE_APP_API_ENV: $DEV_VUE_APP_API_ENV
    DEPLOY_VUE_APP_API_PATH: $DEV_VUE_APP_API_PATH
  tags:
    - share-dev-nodejs
  stage: deploy
  only:
    - master
  script:
    - yarn --ignore-engines
    - yarn build
    - cp -R dist /var/www/platform-comm-f2e/dist_new
    - mv /var/www/platform-comm-f2e/dist /var/www/platform-comm-f2e/dist_old
    - mv /var/www/platform-comm-f2e/dist_new /var/www/platform-comm-f2e/dist
    - rm -rf /var/www/platform-comm-f2e/dist_old
    
deploy:test:
  environment:
    name: test
    url: $TEST_ENVIRONMENT_URL
  variables:
    DEPLOY_VUE_APP_API_ENV: $TEST_VUE_APP_API_ENV
    DEPLOY_VUE_APP_API_PATH: $TEST_VUE_APP_API_PATH
  tags:
    - platform-comm-f2e-test-machine
  stage: deploy
  only:
    - /^.*-beta.*$/
  except:
    - branches
  script:
    - yarn install
    - yarn build
    - mv dist /var/www/platform-comm-f2e/dist_gitlabrunner
    - mv /var/www/platform-comm-f2e/dist_deploy /var/www/platform-comm-f2e/dist_old
    - mv /var/www/platform-comm-f2e/dist_gitlabrunner /var/www/platform-comm-f2e/dist_deploy
    - rm -rf /var/www/platform-comm-f2e/dist_old
