stages:
  - deploy

before_script:
  - yarn --ignore-engines

deploy:develop:
  environment:
    name: develop
    url: $ENVIRONMENT_URL_DEV
  tags:
    - share-dev-nodejs
  stage: deploy
  only:
    - master
  script:
    - yarn build
    - cp -R dist /var/www/platform-comm-f2e/dist_new
    - mv /var/www/platform-comm-f2e/dist /var/www/platform-comm-f2e/dist_old
    - mv /var/www/platform-comm-f2e/dist_new /var/www/platform-comm-f2e/dist
    - rm -rf /var/www/platform-comm-f2e/dist_old